sudo: required
dist: trusty
language: node_js
node_js:
  - "8.0"
cache:
  directories:
    - node_modules
install:
  - npm install
before_script:
  - export RELEASE_HEAD=$(git rev-parse --short HEAD | cut -c1-7)
  - export RELEASE_HEAD_LONG=$(git rev-parse HEAD)
  - export CI=false
script:
  - npm install
  - npm run build
after_script:
  - cd build/
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "passport-tree"
  skip_cleanup: true
  region: $AWS_DEFAULT_REGION
  local_dir: build
